-- Migration: Add synonym_suggestions table voor GPT-4 synonym workflow
-- Created: 2025-10-09
-- Purpose: Enables GPT-4 suggest + human approve workflow for juridische synoniemen
--
-- Table: synonym_suggestions
-- - Stores synonym candidates generated by GPT-4
-- - Tracks approval status (pending/approved/rejected)
-- - Supports human review workflow
-- - Enables audit trail for synonym curation

-- Create synonym_suggestions table
CREATE TABLE IF NOT EXISTS synonym_suggestions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hoofdterm TEXT NOT NULL,
    synoniem TEXT NOT NULL,
    confidence DECIMAL(3,2) NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    rationale TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewed_by TEXT,
    reviewed_at TIMESTAMP,
    rejection_reason TEXT,
    context_data TEXT, -- JSON string met extra context (definitie, model, etc.)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index voor efficient filtering op status
CREATE INDEX IF NOT EXISTS idx_synonym_suggestions_status
ON synonym_suggestions(status);

-- Index voor zoeken op hoofdterm
CREATE INDEX IF NOT EXISTS idx_synonym_suggestions_hoofdterm
ON synonym_suggestions(hoofdterm);

-- Composite index voor hoofdterm + status queries (veelvoorkomend pattern)
CREATE INDEX IF NOT EXISTS idx_synonym_suggestions_hoofdterm_status
ON synonym_suggestions(hoofdterm, status);

-- Index voor confidence-based filtering (high confidence suggestions)
CREATE INDEX IF NOT EXISTS idx_synonym_suggestions_confidence
ON synonym_suggestions(confidence DESC);

-- Index voor tijdgebaseerde queries (recent suggestions, review queue)
CREATE INDEX IF NOT EXISTS idx_synonym_suggestions_created_at
ON synonym_suggestions(created_at DESC);

-- Unique constraint: voorkom dubbele suggesties (hoofdterm + synoniem)
CREATE UNIQUE INDEX IF NOT EXISTS idx_synonym_suggestions_unique_pair
ON synonym_suggestions(hoofdterm, synoniem);

-- Trigger: Update updated_at timestamp bij wijzigingen
CREATE TRIGGER IF NOT EXISTS update_synonym_suggestions_timestamp
AFTER UPDATE ON synonym_suggestions
BEGIN
    UPDATE synonym_suggestions
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.id;
END;

-- Verification queries (commented out - voor handmatige checks)
-- SELECT COUNT(*) as table_exists FROM sqlite_master
-- WHERE type='table' AND name='synonym_suggestions';
--
-- SELECT * FROM sqlite_master WHERE type='index' AND tbl_name='synonym_suggestions';
