"""Maak uitsluitend nieuwe B-v3-documenten; behoud alle bestaande versies."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
t = (root / "onderzoek-b-v2.md").read_text()

def vervang(oud, nieuw):
    global t
    assert t.count(oud) == 1, (oud[:100], t.count(oud))
    t = t.replace(oud, nieuw)

def voeg_na(anker, tekst):
    vervang(anker, anker + "\n\n" + tekst)

vervang("# INT-02 — onafhankelijk onderzoek B v2", "# INT-02 — herzien onderzoek B v3")
vervang("Zelfcontrole vóór overdracht: de volledige onafhankelijke v1 blijft behouden. Deze v2 preciseert alleen de logische valkuil in casus C57 en herstelt de weergave van één voorgestelde tabelrij; geen conclusies van A of ontvangen kruisreview gelezen/verwerkt.", "(v3: RA-B-25) Verwerking van de ontvangen review RA-B-01 t/m RA-B-25, met beslissingen en vindplaatsen in [verwerking-b-v1.md](verwerking-b-v1.md). V1 en v2 blijven ongewijzigd. De opbouw van v2 blijft behouden; alleen reviewgebonden correcties en aanvullingen zijn aangebracht. Chris heeft op 25 september INT-10 voor afzonderlijk onderzoek geparkeerd: de waarneming blijft, zonder besluitvraag of wijzigingsafhankelijkheid voor INT-02.")
vervang("fase: onafhankelijke eerste versie, gereed voor overdracht en kruisreview.", "fase: verwerking ontvangen review, gereed voor synthese.")
vervang("A's nieuwe onderzoek, kruisreviews en synthese zijn vóór opslag van zowel v1 als deze v2 niet gelezen.", "A's nieuwe onderzoek en kruisreviews zijn pas na opslag van de onafhankelijke v1/v2 en expliciete overdracht gelezen; een gezamenlijke synthese is nog niet gecontroleerd.")
voeg_na("### Bronregister en leeswijzer", "(v3: RA-B-07) (v3: RA-B-09) Aanvullende reviewbasis: `../a-claude-cli/review-a-op-b-v1.md` (SHA-256 `382792b0515d05d3483d832779738482fbf592a343cf7911cf43f2393d7f8203`), A-P1/P2 en A-P3 (`proef-p3-int10-melding.py`, `p3-uitkomsten.json`, `proeflog-a-v2-p3.md`). A-P3 is een andere proef dan B-P3 (cleaning). Ontvangstlog bevestigt de overdracht. Nieuwe bronbinding in `bewijs/verwerking-bronbinding-v1.json`; gerichte statische controle in `bewijs/verwerking-broncontrole-v1.md`. Geen nieuwe appproef nodig: ontvangen proef en code lossen de feitelijke vragen op. A-P3-exit 0 is door A afgeleid uit tooluitvoer, niet door B geobserveerd.")
vervang("[I] Een algemeen verbod op voorwaarden kan afleidingscriteria en noodzakelijke lidmaatschapsgrenzen verwijderen. Het normconflict ligt al in de instructies; P1 bewijst **niet** dat de huidige validator dergelijke criteria foutief afkeurt: deze geeft juist altijd een open review. “De app verbiedt indien” is dus te ongenuanceerd: G verbiedt het, T signaleert het en laat het oordeel open.", "(v3: RA-B-07) [I/W] Een algemeen voorwaardenverbod kan afleidingscriteria en lidmaatschapsgrenzen verwijderen. B-P1 filtert violations op INT-02: alleen **die evaluator** geeft altijd open review, zonder eigen inhoudelijke afkeur. Dit zegt niet dat de gehele app alleen signaleert. A-P1 en A-P3 bevestigen buurafkeur op `indien`: C04 krijgt INT-01 warning/low en INT-10 error/critical, beide met patroonmelding en ‘Herschrijf de zin zodat de gedetecteerde patronen niet voorkomen.’ C05 krijgt beide pass. Het is een servicewaarneming, geen gemeten browseractie of semantisch equivalente A/B-tekstproef. INT-10 blijft op instructie van Chris een **geparkeerde waarneming voor het INT-10-dossier**: geen besluitpunt en geen afhankelijkheid voor INT-02. INT-01 behoudt zijn afzonderlijke open eigenaarschap.")
voeg_na("**Normvariant N-A, eng:** alleen discretionaire beslisregels uitsluiten, deterministische afleiding behouden; overige voorschriften niet zonder eigen grond INT-02-afkeuren. Voordeel: dicht bij de expliciete Beslisregel-definitie. Nadeel: laat deterministische behandelinstructies onder INT-02 onbeslist en benut ASTRA's gedragsachtergrond beperkt.", "(v3: RA-B-01) C02 dekt onder de bedoelde verplichtingslezing geen discretionaire afweging: onder N-A dus geen INT-02-VN, onder N-B1 wel bij bevestigde actorvoorschriftfunctie. Daarmee verklaart N-A het ASTRA-ONJUIST-label niet zonder aanvullende grond. Dat is extra steun voor N-B1 naast de Achtergrond, maar geen bewijs dat ieder ‘moet’ een actorvoorschrift is. De historische bronlabeling blijft apart van onze variantverwachting bewaard.")
voeg_na("### V01 — exacte gezamenlijke norm N-B1", "(v3: RA-B-02) (v3: RA-B-03) (v3: RA-B-05) De onderstaande norm blijft inhoudelijk behouden. ‘Deterministisch’ kwalificeert de **afleiding**, niet elke definitie of eensluidendheid tussen lezers. Epistemische beoordeling van een kwalitatief kenmerk is geen actor-discretie. De actorvoorschriftgrens is lokale operationalisering met ASTRA-steun, geen al besloten gelijkstelling. Beschrijvende rechtsgevolgen zijn geen zelfstandige extra keuze naast K1; concrete functieambiguïteit blijft een informatievraag.")
voeg_na("### V02 — veldrollenmatrix (genereren-en-toetsen §A)", "(v3: RA-B-12) (v3: RA-B-13) De rollen blijven behouden. Waar de matrix afzonderlijke toelichting, bronverantwoording of relatievoorstellen noemt, betreft dat ondersteunende invoer of een afzonderlijk opgedragen taak/kanaal, **geen extra uitvoer uit de één-zin-generatieaanroep**. Voor G geldt V05; een nieuw toelichtingskanaal is niet door dit onderzoek beschikbaar of verplicht gesteld.")
voeg_na("## Q3. Samenhang en eigenaarschap", "(v3: RA-B-07) (v3: RA-B-20) Aanvullende ketencontext: `INT-10.json:15,37–45` draagt `indien` als generic/automated/scored; A-P3 legt de concrete melding vast. **Geparkeerd voor later INT-10-onderzoek**, geen nieuw besluit of afhankelijkheid hier. A-P2 toont in de standaard geregistreerde modules ook ESS-03-G ‘behoud inhoudelijk noodzakelijke namen en voorwaarden’ en STR-09-✅ ‘Een persoon met een paspoort of, indien niet beschikbaar, een identiteitskaart’. Dat staat op gespannen voet met INT-02-G ‘Vermijd voorwaardelijke formuleringen’. Geen volledige prompt/modelrun gemeten. N-B1/V05 haalt het algemene vormverbod uit INT-02; dat bewijst niet dat alle buurafkeur of alle promptspanning in de app daarmee verdwijnt.")
voeg_na("### W01 — hergebruik en nieuwe proeven", "(v3: RA-B-09) (v3: RA-B-10) De smalle hergebruikgrens en bestaande proefuitkomsten blijven gelijk. ‘Vooraf’ bij `proefplan-v1.md` is procesregistratie uit de eigen uitvoering; een onafhankelijk vóór de run verankerde verwachtingshash ontbreekt. Eindhash/mtime bewijzen die volgorde niet zelfstandig. Geen achteraf bewijs fabriceren. Bij een latere proef verwachtingshash vóór de run opnemen in het uitvoeringsrecord. Dit verandert de geobserveerde software-uitkomsten niet.")
voeg_na("### F04 — routeoverzicht", "(v3: RA-B-11) A bevestigt de gescheiden importroutes en beperkte opslaghelper. Gerichte codecontrole ondersteunt de gateprecisering: `models.py:150–153` neemt severity over, niet severity_level; `_evaluate_gate:741–742` vergelijkt severity met critical/high. A-P3 levert error respectievelijk warning. Die items raken via dit onveranderde kanaal dus niet de critical/high-tak; andere gateblokkades kunnen wel blijven bestaan. Geen uitgevoerde vaststelproef of claim dat vaststellen lukt.")
voeg_na("### V04 — evaluatoropties", "(v3: RA-B-17) **K2-detail signaalhulp:** optie S0 behoudt bestaande signalen plus beoordeling van de gehele kern; optie S1 voegt beperkte zinsdeelmarkers toe, bijvoorbeeld ‘van oordeel is’ en ‘naar eigen inzicht’. Voorkeur B: S1 als te besluiten O1-detail, met volledig citaat/positie en geen woord→fail. Los ‘acht’, ‘redelijk’ of ‘passend’ is te ambigu als bewijs; ‘moet’ is evenmin beslissend. Overlap met ARAI-04 is geen principieel verbod op zo’n leeshulp: K-8 staat eigen onderbouwing per regel toe. Selectie en bruikbaarheid zijn nog niet empirisch bewezen. C13/CO-C83, C02/C52 en een beschrijvende discretionaire bevoegdheid onderscheiden de opties. Geen nieuwe regexen geïmplementeerd.")
g_oud = next(x for x in t.split('\n\n') if x.startswith('> Formuleer een beschrijvende afbakening'))
g_nieuw = "> Formuleer uitsluitend de definitiekern als één zin binnen de gegeven betekenis en context; voeg geen vraag, bronverantwoording, onzekerheidsmelding, toelichting of procesinstructie aan de uitvoer toe. Gebruik geen handelingsvoorschrift, behandelprocedure of discretionaire beslisregel als definitiekern. Behoud onderbouwde begripscriteria, voorwaarden en uitzonderingen. Definieer een afleidbaar begrip met de deterministische afleiding uit de aangeleverde relevante feiten en conventies. De woorden ‘indien’, ‘mits’, ‘tenzij’ en ‘alleen als’ zijn toegestaan wanneer zij de afbakening dragen; vermijd ze niet ten koste van betekenis. Beschrijf een constitutieve bevoegdheid, beslissing of rechtsgevolg wanneer die het begrip bepaalt, zonder de uitoefening ervan voor te schrijven. Behoud noodzakelijkheid, voldoende voorwaarden, bereik, negatie, aantallen en termijnen. Verzin geen criterium, bron, context, actorafweging of goedkeuring. Geef bij ontbrekende maar niet strijdige betekenisgrond uitsluitend een voorlopige kern voor zover de beschikbare grond die draagt, zonder melding van voorlopigheid in de zin; een gerichte vraag en de zichtbare voorlopige status horen bij de afzonderlijke beoordeling en appweergave. Leg bij strijdige grond geen betwiste betekenis stil in de kern vast."
vervang(g_oud, "(v3: RA-B-13)\n\n" + g_nieuw)
app_oud=next(x for x in t.split('\n\n') if x.startswith('Appvoorwaarde vóór dit G-blok'))
vervang(app_oud, "(v3: RA-B-13) Appvoorwaarde vóór G: term/context aanwezig (K-9). De één-zin-uitvoer bevat alleen kern; bronadministratie blijft invoer/appbeheer, geen gevraagde extra modeltekst. Volgens het ESS-03-patroon (`json_based_rules_module.py:335–354`) loopt één noodzakelijke verduidelijkingsvraag via T: bij O1 de reviewerhulp, bij gekozen O2 de inhoudelijke O-uitkomst. Dit beweert niet dat de huidige INT-02-evaluator al zo'n vraag maakt. Kan de betekenisgrond geen verantwoorde kern dragen, dan moet de latere appuitvoering de ontbrekende keuze zichtbaar afhandelen zonder een fictieve kern als succes op te slaan; de precieze onthoudingsafhandeling vóór/na G is een uitvoeringsacceptatiepunt. Geen nieuw meerledig modeluitvoerformaat of toelichtingskanaal via deze prompt afdwingen. H blijft een afzonderlijk gevraagd voorstel onder DEF-638. Test C04/C50/C51/C53/C54/C56/C60/C64, inclusief afwezigheid van extra uitvoer en behoud van betekenis. Bij N-A het actorvoorschriftdeel in N/G/T gezamenlijk versmallen.")
voeg_na("### V06 — T, exacte toetsinstructie", "(v3: RA-B-14) (v3: RA-B-15) (v3: RA-B-16) Normgrens, uitzonderingen en statusmapping blijven behouden. De G-uitvoerbeperking wijzigt T’s norm niet: een vraag hoort bij de beoordeling, niet in de kern. De omringende relevante bijzin/zin moet letterlijk geciteerd worden met positie; `_reden_met_passages:176–192` levert nu alleen regexmatches. INT-02-N/G/T aansluiten is een eigen eis; bestaande INT-10-buurafkeur wordt afzonderlijk geregistreerd en maakt een INT-10-wijziging niet tot voorwaarde voor deze voorstellen.")
voeg_na("### V07 — H, exacte diagnose- en herstelinstructie (ontwerp onder DEF-638)", "(v3: RA-B-08) (v3: RA-B-18) A’s statische ketenwaarneming is bevestigd: `_herstelbare_overtredingen:1976–1999` kan gewone INT-01/INT-10-violations doorgeven; uitvoering vereist ook enable_enhancement en een enhancement_service (:1263–1275). De container injecteert `None` (`container.py:384`). Dit is **latent risico, geen uitgevoerd herstel**. INT-10-specifieke opvolging is geparkeerd. De al algemene H-stopregel blijft: patroonafkeur zonder aangetoonde normgrond mag geen betekeniswijziging dragen. Dat vereist geen voorafgaande INT-10-wijziging en activeert niets. Een apart toelichtingsvoorstel hieronder behoort uitsluitend tot een afzonderlijk ontworpen/gevraagde H-taak, nooit tot de huidige één-zin-G-uitvoer.")
voeg_na("### V08 — concrete vervangplaatsen: huidig → probleem → exact voorstel → casus", "(v3: RA-B-21) (v3: RA-B-22) Aanvullend exact voorstel voor `runtime_contract.example_pair_reason`: **‘Het ASTRA-paar verschilt in het modale werkwoord moet. Dat raakt ARAI-04 en kan onder de bevestigde voorschriftlezing ook de lokale INT-02-functiegrens raken. Onder de enge discretionaire variant is zonder discretionaire grond geen INT-02-afkeur bewezen. Het paar blijft een reviewgeval; ASTRA noemt het weinig sprekend. Het woord bewijst op zichzelf geen actorfunctie, rolomkering of betekenisbehoud bij verwijdering.’** Behoud `review_policy`; K3 omvat deze reden en aanvullende functiegevallen. Ook de ONJUIST-zin dwingt niet grammaticaal af dat de organisatie onderwerp is: ‘eis die een organisatie moet ondersteunen’ laat de lezing toe dat de eis de organisatie moet ondersteunen. Noch CO’s rolomkering, noch A’s stellige onderwerpclaim is bronfeit. De normatieve verplichtingslezing blijft als casuspremisse zichtbaar.")
voeg_na("### V09 — effectevaluatie met behoudcriteria", "(v3: RA-B-14) (v3: RA-B-24) Registreer in een latere effectproef naast INT-02-uitkomsten ook feitelijke buurafkeur en patroongebaseerde herschrijfsuggesties op de **vooraf als V vastgestelde** criteriumgevallen. A-P1’s groep van zes omvat ook OI/conditionele verwachtingen en is geen zuivere ‘6 van 6 V’-nulmeting; A-P3 levert twee concrete serviceteksten met context, geen equivalentie- of kwaliteitsproef. INT-10 is geparkeerd: geen eis dat deze telling eerst nul wordt, geen gekoppelde INT-10-implementatie of met/zonder-INT-10-interventie in dit onderzoek. Houd buurconfiguratie constant in de INT-02-vergelijking en rapporteer haar invloed als afzonderlijke beperking; bescherm criteria ongeacht een buurmelding.")
t=t.replace('[casusregister](casusregister-b-v2.md)', '[casusregister](casusregister-b-v3.md)')
voeg_na("### V10 — besluiten voor Chris, met voorkeur en gevolg", "(v3: RA-B-25) K1 bundelt A B-1/B-2/B-3/B-6 (functiegrens, criteria, actorvoorschrift en beschrijvende rechtsgevolgen); K2 koppelt aan B-4, met signaalkeuze uit RA-B-17. B-8/B-9 worden als uitvoeringsacceptatie meegenomen, niet als nieuwe normkeuze. K3 koppelt B-5/skill-promptvoorstellen en de aangepaste voorbeeldreden. K4 corrigeert A’s eerdere afleiding van geen-gate uit 15 september. K5 bundelt het H-ontwerp. **A B-7/INT-10 staat door Chris’ latere instructie niet in de besluitenlijst en blokkeert geen INT-02-voorstel.** INT-01 blijft het bestaande afzonderlijke dossier; geen nieuwe gezamenlijke buurregelkeuze.")
vervang('C03/C52 tegenover C50/C53/C69; ASTRA-redactievragen zichtbaar', 'C02/C03/C52 tegenover C50/C53/C69; N-A dekt ASTRA’s foutlabel niet zonder aanvullende grond; redactievragen zichtbaar (v3: RA-B-01)')
vervang('O1 menselijke passagehulp binnen bestaande integrale review, met zichtbare reden/grond en open status', 'O1 menselijke passagehulp met zichtbare reden/grond/open status; beperkte S1-zinsdeelmarkers als expliciet O1-detail (v3: RA-B-17)')
vervang('bestaand ASTRA-paar met review_policy en nieuwe functiegevallen', 'bestaand ASTRA-paar met review_policy, gecorrigeerde example_pair_reason en nieuwe functiegevallen (v3: RA-B-21)')
voeg_na("Geen nieuwe besluitvraag: appbrede contextplicht K-9, definitief geen totaalscore, uitsluitend toetsen verandert niets. Geen keuze van model onder DEF-815, geen nieuwe Linear-issue of codewijziging. Ontbrekende uitvoeringseigenaar voor effectmeting staat expliciet open; A neemt V09 mee in het gezamenlijke advies en Chris' eventuele uitvoeringsopdracht.", "(v3: RA-B-23) **Dekking veertien onderdelen:** 1 doel / 2 norm-besluiten / 3 toepasselijkheid: Q1 en V10; 4 context / 5 definitiebronnen / 6 ontologie / 7 aanvullingen: Q2/V02; 8 appgedrag / 10 status-score-poorten: Q4/V06/K4; 9 skills-prompts: V05/V08; 11 proeven: W01/P1–P4 en ontvangen A-P3; 12 samenhang: Q3; 13 verbeteringen-review: Q5 en verwerking-b-v1; 14 acceptatie-overdracht: V09, casusregister-v3 en §7. Aanwezigheid betekent niet dat open route- en effectbewijs geleverd is.")
start=t.index('**Aan A:**')
t=t[:start]+"""(v3: RA-B-25) **Overdracht aan A/coördinator:** ontvangen RA-B-01…25 zijn puntgewijs verwerkt in `verwerking-b-v1.md`; herziene basis is dit v3 met `casusregister-b-v3.md`. B’s review op A blijft `review-b-op-a-v1.md` plus het afzonderlijke vindplaatserratum. V1/v2 en eerder bewijs blijven ongewijzigd. Nog nodig: A’s verwerking in de synthese opnemen en de volledige synthese op verzoek aan B overdragen voor één controle op weglatingen, juiste standpuntweergave, resterende tegenspraken en betekenisverlies, inclusief G/T-aansluiting. Alleen materiële wijzigingen rechtvaardigen gerichte vervolgcontrole.

Deze bijdrage voltooit **B’s verwerking van de ontvangen review**, geen gezamenlijke synthese of implementatie. Open blijven norm-/productkeuzes K1–K5, uitvoeringseigenaar en uitvoering/effectbewijs zoals V09 benoemt, DBT-bronleemte en concrete betekenisambiguïteiten. INT-10 is geparkeerd, niet een onbeslist INT-02-besluit. Eindtijd en hashes staan in `manifest-b-v3.json`; de eigen manifesthash staat extern in het eindbericht.
"""

c=(root/'casusregister-b-v2.md').read_text()
c=c.replace('# INT-02 — casusregister onderzoek B v2','# INT-02 — casusregister onderzoek B v3',1)
c=c.replace('25 september 2026. Zelfcontrole vóór overdracht: v1 blijft behouden. Alleen C57 is inhoudelijk gepreciseerd; scenario en INT-02-uitkomst blijven gelijk, de onterechte suggestie van logische equivalentie vervalt. Geen ontvangen kruisreview verwerkt.', '(v3: RA-B-01) (v3: RA-B-13) 25 september 2026. V1/v2 blijven ongewijzigd. C02 krijgt expliciete normvariantverwachtingen. G-uitvoer is verduidelijkt voor alle rijen en de geraakte G-voorbeelden; de kernteksten en scenario-IDs blijven gelijk. C57 behoudt de eerdere correctie. Geen nieuwe app-/modelproef.')
c=c.replace('`onderzoek-b-v2.md`','`onderzoek-b-v3.md`')
c=c.replace('VN in de bedoelde ASTRA-voorbeeldlezing; uitsluitend het woord `moet` bewijst in andere gevallen geen INT-02-overtreding.', '(v3: RA-B-01) VN onder N-B1 bij bevestigde actorvoorschriftlezing; onder N-A zonder discretionaire grond geen INT-02-VN. Het historische ASTRA-ONJUIST-label blijft bronfeit, geen bewijs dat N-A die lezing dekt. Alleen `moet` bewijst de functie niet.')
anchor='Een concept, open beoordeling of vaststelling is geen automatisch V. Geen totaalscore.'
assert anchor in c
c=c.replace(anchor,anchor+'\n\n(v3: RA-B-13) Voor **alle G-kolommen** geldt: alleen één definitiekern in de generatie-uitvoer, geen vraag/toelichting/bronverantwoording/statusregel. Een noodzakelijke vraag loopt via T/reviewerhulp; appstatus toont voorlopigheid buiten de kern. Afzonderlijke bron- of procesinformatie is invoer/appbeheer of een afzonderlijk gevraagde taak, geen tweede G-uitvoerblok. Zonder gedragen kern geen gefingeerd succes; de latere appafhandeling moet dit aantonen. H is afzonderlijk en nog niet actief.')
c=c.replace('Begrip afbakenen, behandelinstructie apart; bij ontbrekende kernbron geen vervangend kenmerk verzinnen.', '(v3: RA-B-13) Alleen begripskern; behandelregel niet in uitvoer. Bij ontbrekende kernbron geen kenmerk verzinnen; verduidelijking via T/app.')
c=c.replace('Afleidingscriteria behouden; geen discretionair oordeel invoegen; bronadministratie apart.', '(v3: RA-B-13) Alleen kern met afleidingscriteria; geen discretionair oordeel. Bronadministratie blijft buiten deze modeluitvoer.')
c=c.replace('Deze handelingsrichtlijn niet als definiens opleveren; vraag bron voor het beoogde begrip.', '(v3: RA-B-13) Handelingsrichtlijn niet als definiens; geen vervangende kern verzinnen. Benodigde bronvraag via T/app, niet in de generatiezin.')
c=c.replace('Geen stille synthese of kunstmatig compromis; afzonderlijke vraag naar toepasselijke bron/betekenis.', '(v3: RA-B-13) Geen stille keuze of kunstmatig compromis in een kern. Vraag naar toepasselijke bron/betekenis via T/app; geen vraag als G-uitvoer.')
c=c.replace('Eerste segment als kern, tweede hoogstens afzonderlijke toelichting met bron; geen nieuw kenmerk toevoegen.', '(v3: RA-B-13) Alleen het zelfstandig gedragen eerste segment als kern; geen tweede procesblok in G-uitvoer. Een toelichtingsvoorstel vraagt een afzonderlijke taak/kanaal; geen nieuw kenmerk.')
c=c.replace('Historischzelfde criterium zonder voorwaardewoord;', 'Historisch criterium zonder voorwaardewoord;')
c += '\n(v3: RA-B-07) (v3: RA-B-24) Ontvangen A-P3 is aanvullend **servicebewijs** bij C04/C05 met context: C04 INT-01/INT-10-fail met patroonsuggestie, C05 beide pass; INT-02 beide J. Geen nieuwe INT-02-normverwachting en geen bewijs dat de teksten equivalent zijn. INT-10 is door Chris geparkeerd voor een eigen dossier; geen herstelgrond, besluitpunt of wijzigingsvoorwaarde voor INT-02. G/T/H-referenties blijven per regel beoordeeld.\n'

for name in ('onderzoek-b-v3.md','casusregister-b-v3.md'):
    assert not (root/name).exists(), name
with (root/'onderzoek-b-v3.md').open('x') as f: f.write(t)
with (root/'casusregister-b-v3.md').open('x') as f: f.write(c)
print('Nieuwe v3-documenten geschreven; v2 uitsluitend gelezen.')
