"""Tests voor scripts/ci/check_lock_sync.sh (DEF-559/DEF-711).

Deze gate bewaakt of de gecommitte lock hoort bij de gecommitte .in-bron. Hij
stond eerder structureel rood — zelfs direct na `make lock` — en werd daarom
genegeerd, waarna een echte desync ongemerkt op main landde: `setuptools` viel
uit requirements.txt terwijl requirements.in het pinde. Zonder test bewaakt niets
dat de gate zijn discriminerende vermogen houdt.

`uv` wordt gestubd. Een echte resolve kost seconden en netwerk, en zou de test
afhankelijk maken van PyPI-beschikbaarheid; de stub maakt alle uitkomsten
deterministisch en toetst precies wat dit script zelf doet — het vergelijken van
de resolve-uitvoer met de gecommitte lock, en het onderscheiden van de
foutklassen.

Exit-codes van het script: 0 sync, 1 desync, 2 resolve-fout, 3 preconditie.
Die zijn alleen zichtbaar bij een directe aanroep; `make lock-check` vertaalt
elke fout naar make-exitcode 2.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit]

SCRIPT = (
    Path(__file__).parent.parent.parent.parent / "scripts" / "ci" / "check_lock_sync.sh"
)

# De eerste twee regels van een uv-lock zijn de header; het script strips die
# voor de vergelijking, omdat de check met --no-header compileert.
HEADER = "# This file was autogenerated by uv via the following command:\n#    uv pip compile\n"

# De bodies dragen hashes, net als de echte lockfiles. Zonder hashes in de
# fixture blijft een scriptmutatie die `--hash`-regels uit de vergelijking
# strip onzichtbaar, terwijl die een gemanipuleerde lock groen zou verklaren.
LOCK_BODY = (
    "voorbeeld==1.0.0 \\\n"
    "    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111\n"
    "    # via -r requirements.in\n"
)
DEV_LOCK_BODY = (
    "voorbeeld-dev==2.0.0 \\\n"
    "    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222\n"
    "    # via -r requirements-dev.in\n"
)

# De pin die in het compile-doel moet staan wil het als versievoorkeur gelden.
# De stub gebruikt dit om te bepalen of het script de lock daadwerkelijk heeft
# gekopieerd — niet of het bestand toevallig niet leeg is.
RUNTIME_PIN = "voorbeeld==1.0.0"
DEV_PIN = "voorbeeld-dev==2.0.0"

# Wat de stub in write-modus boven de body schrijft (geen --no-header), zodat
# een assertie op de volledige uitvoer één bron deelt met de stub zelf.
VERWACHTE_WRITE_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    make lock\n"
)


def _fake_uv(
    bin_dir: Path,
    *,
    runtime_body: str,
    dev_body: str,
    exit_code: int = 0,
    dev_exit_code: int = 0,
    body_zonder_voorkeur: str | None = None,
    dev_body_zonder_voorkeur: str | None = None,
    foutmelding: str = "error: kan niet resolven",
) -> None:
    """Zet een uv-stub op PATH die zich als een strenge uv gedraagt.

    De stub is bewust wantrouwig, want een toegeeflijke stub laat kapotte
    varianten van het script groen: hij schrijft dan nog steeds de verwachte
    body en de suite merkt niets. Daarom weigert deze stub onbekende vlaggen,
    controleert hij dat bron- en constraintpaden bestaan, en bepaalt hij de
    versievoorkeur op INHOUD.

    Dat laatste is het cruciale punt. uv gebruikt een bestaand `-o`-bestand als
    versievoorkeur. Een stub die alleen kijkt of dat bestand niet leeg is, is te
    zwak: vervang de kopieerstap door iets dat enkel de header schrijft en het
    doel is niet-leeg maar bevat geen enkele pin — echte uv zou dan vrij
    upgraden, terwijl zo een stub gewoon de goede body teruggeeft. Deze stub
    kijkt daarom of de verwachte pin daadwerkelijk in het doel staat.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    uv = bin_dir / "uv"
    vrije_body = (
        body_zonder_voorkeur if body_zonder_voorkeur is not None else runtime_body
    )
    dev_vrije_body = (
        dev_body_zonder_voorkeur if dev_body_zonder_voorkeur is not None else dev_body
    )
    # De stub legt zijn volledige argv vast, zodat tests kunnen toetsen wélke
    # vlaggen het script meegeeft. Zonder die controle blijft het wegvallen van
    # -c of --no-header onzichtbaar: de gate gaat dan stuk terwijl alle tests
    # groen blijven.
    argv_log = bin_dir / "argv.log"
    uv.write_text(
        "#!/usr/bin/env bash\n"
        f'printf "%s\\n" "$*" >> {str(argv_log)!r}\n'
        'if [ "$1" != "pip" ] || [ "$2" != "compile" ]; then\n'
        '  echo "error: onverwacht subcommando $1 $2" >&2\n'
        "  exit 2\n"
        "fi\n"
        "shift 2\n"
        'bron=""\n'
        'doel=""\n'
        'constraint=""\n'
        # Echte uv schrijft altijd een header, tenzij --no-header meekomt. De
        # stub volgt dat, zodat een write-dan-check-round-trip de headerstrip
        # van `vergelijk()` werkelijk doorloopt in plaats van hem over te slaan.
        "geen_header=0\n"
        "while [ $# -gt 0 ]; do\n"
        '  case "$1" in\n'
        "    --universal|--generate-hashes) ;;\n"
        "    --no-header) geen_header=1 ;;\n"
        "    --custom-compile-command) shift ;;\n"
        "    -o) shift; doel=$1 ;;\n"
        "    -c) shift; constraint=$1 ;;\n"
        "    -*)\n"
        '      echo "error: onbekende vlag $1" >&2\n'
        "      exit 2\n"
        "      ;;\n"
        # Exact één positionele bron. Alleen de eerste onthouden liet een
        # tweede bron ongemerkt passeren, terwijl echte uv daarop een andere
        # resolutie geeft.
        "    *)\n"
        '      if [ -n "$bron" ]; then\n'
        '        echo "error: meer dan één bronbestand ($bron en $1)" >&2\n'
        "        exit 2\n"
        "      fi\n"
        "      bron=$1\n"
        "      ;;\n"
        "  esac\n"
        "  shift\n"
        "done\n"
        # De bronnaam moet exact kloppen. Alleen op bestaan controleren is te
        # zwak: dan valt elk pad dat niet op requirements-dev.in eindigt in de
        # runtime-tak, en blijft een script dat per ongeluk requirements.txt
        # compileert onopgemerkt.
        'basisnaam=$(basename "$bron")\n'
        'if [ "$basisnaam" != "requirements.in" ] && '
        '[ "$basisnaam" != "requirements-dev.in" ]; then\n'
        '  echo "error: onverwacht bronbestand $bron" >&2\n'
        "  exit 2\n"
        "fi\n"
        'if [ ! -f "$bron" ]; then\n'
        '  echo "error: bronbestand $bron bestaat niet" >&2\n'
        "  exit 2\n"
        "fi\n"
        # Aparte exitcode per tak, zodat een fout die alleen tijdens de
        # dev-resolve optreedt afzonderlijk te testen is.
        'if [ "$basisnaam" = "requirements-dev.in" ]; then\n'
        f"  if [ {dev_exit_code} -ne 0 ]; then\n"
        f"    echo {foutmelding!r} >&2\n"
        f"    exit {dev_exit_code}\n"
        "  fi\n"
        "else\n"
        f"  if [ {exit_code} -ne 0 ]; then\n"
        f"    echo {foutmelding!r} >&2\n"
        f"    exit {exit_code}\n"
        "  fi\n"
        "fi\n"
        'if [ -n "$constraint" ] && [ ! -f "$constraint" ]; then\n'
        '  echo "error: constraint $constraint bestaat niet" >&2\n'
        "  exit 2\n"
        "fi\n"
        'if [ -z "$doel" ]; then\n'
        '  echo "error: geen -o meegegeven" >&2\n'
        "  exit 2\n"
        "fi\n"
        # Het voorkeurbestand mag geen hashes bevatten. Echte uv neemt die
        # namelijk over in plaats van ze te herberekenen, waardoor een lock met
        # gemanipuleerde hashes zijn eigen corruptie erft en de gate groen
        # meldt. Zonder deze controle houdt precies die oude implementatie —
        # de volledige lock naar het doel kopiëren — de suite groen.
        'if [ -f "$doel" ] && grep -q -- "--hash=" "$doel"; then\n'
        '  echo "error: voorkeurbestand bevat hashes; uv zou ze overnemen" >&2\n'
        "  exit 2\n"
        "fi\n"
        # Schrijft de uitvoer, voorafgegaan door een header tenzij --no-header
        # meekwam. %b, niet %s: de body komt als Python-repr binnen, dus met
        # \n-escapes die de shell nog moet interpreteren.
        "schrijf_uitvoer() {\n"
        '  : > "$doel"\n'
        '  if [ "$geen_header" = 0 ]; then\n'
        "    printf '%b' '# This file was autogenerated by uv via the following"
        ' command:\\n#    make lock\\n\' >> "$doel"\n'
        "  fi\n"
        '  printf \'%b\' "$1" >> "$doel"\n'
        "}\n"
        'case "$bron" in\n'
        "  *requirements-dev.in)\n"
        f'    if grep -qF {DEV_PIN!r} "$doel" 2>/dev/null; then\n'
        f"      schrijf_uitvoer {dev_body!r}\n"
        "    else\n"
        f"      schrijf_uitvoer {dev_vrije_body!r}\n"
        "    fi\n"
        "    ;;\n"
        "  *)\n"
        f'    if grep -qF {RUNTIME_PIN!r} "$doel" 2>/dev/null; then\n'
        f"      schrijf_uitvoer {runtime_body!r}\n"
        "    else\n"
        f"      schrijf_uitvoer {vrije_body!r}\n"
        "    fi\n"
        "    ;;\n"
        "esac\n",
        encoding="utf-8",
    )
    uv.chmod(0o755)


def _repo(tmp_path: Path) -> Path:
    """Bouw een minimale repo-structuur met .in-bronnen en locks."""
    root = tmp_path / "repo"
    root.mkdir()
    (root / "requirements.in").write_text("voorbeeld==1.0.0\n", encoding="utf-8")
    (root / "requirements-dev.in").write_text(
        "voorbeeld-dev==2.0.0\n", encoding="utf-8"
    )
    (root / "requirements.txt").write_text(HEADER + LOCK_BODY, encoding="utf-8")
    (root / "requirements-dev.txt").write_text(HEADER + DEV_LOCK_BODY, encoding="utf-8")
    return root


def _draai(root: Path, bin_dir: Path | None) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    # Beperk PATH tot de stub plus de systeempaden die bash/diff/sed leveren,
    # zodat een echte uv uit de dev-omgeving de test niet stilletjes overneemt.
    basis = "/usr/bin:/bin:/usr/sbin:/sbin"
    env["PATH"] = f"{bin_dir}:{basis}" if bin_dir else basis
    return subprocess.run(
        ["bash", str(SCRIPT)],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )


def _draai_write(
    root: Path, bin_dir: Path, *extra: str, tmpdir: Path | None = None
) -> subprocess.CompletedProcess[str]:
    """Zoals `_draai`, maar met --write en optionele extra argumenten."""
    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{bin_dir}:/usr/bin:/bin:/usr/sbin:/sbin"
    if tmpdir is not None:
        env["TMPDIR"] = str(tmpdir)
    return subprocess.run(
        ["bash", str(SCRIPT), "--write", *extra],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )


def test_lock_in_sync_geeft_exit_0(tmp_path):
    """De gate slaagt wanneer de resolve gelijk is aan de gecommitte lock."""
    root = _repo(tmp_path)
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, resultaat.stderr
    assert "OK:" in resultaat.stdout


def test_lock_wordt_als_versievoorkeur_meegegeven(tmp_path):
    """De kern van DEF-559: de check moet dezelfde voorkeur krijgen als `make lock`.

    uv gebruikt een bestaand -o-bestand als versievoorkeur. Kopieert het script
    de lock niet naar het compile-doel, dan resolvet uv vrij en kiest hij de
    nieuwste versies — waarna de gate rood staat op niets meer dan een upstream
    release. Precies zo faalde deze gate structureel, zelfs direct na `make lock`.

    De stub schrijft een afwijkende body zodra het doel leeg is, dus deze test
    wordt rood als de kopieerstap uit het script verdwijnt.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        body_zonder_voorkeur="voorbeeld==1.1.0\n    # via -r requirements.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De gate hoort groen te zijn: de lock is geldig. Rood betekent dat de "
        f"versievoorkeur niet is meegegeven.\n{resultaat.stderr}"
    )


def test_dev_lock_wordt_als_versievoorkeur_meegegeven(tmp_path):
    """Ook de dev-tak moet zijn lock als voorkeur meekrijgen.

    Het script kopieert twee locks naar het compile-doel. Beide takken kunnen
    onafhankelijk regresseren, dus dekking van de runtime-tak zegt hier niets.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        dev_body_zonder_voorkeur="voorbeeld-dev==2.1.0\n    # via -r requirements-dev.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De dev-lock is geldig; rood betekent dat de versievoorkeur voor de "
        f"dev-tak niet is meegegeven.\n{resultaat.stderr}"
    )


def test_stub_zonder_voorkeur_tak_is_bereikbaar(tmp_path):
    """Zelftest: bewijst dat de `body_zonder_voorkeur`-tak van de stub werkt.

    De voorkeurtest hierboven toont exit 0 wanneer de kopieerstap er is. Zonder
    deze zelftest zou die test ook groen blijven als de stub-tak onbereikbaar
    was — dan zou hij niets bewijzen. Met een lege gecommitte lock is het
    compile-doel leeg, dus de stub schrijft de afwijkende body en de gate hoort
    rood te worden.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text("", encoding="utf-8")
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        body_zonder_voorkeur="voorbeeld==1.1.0\n    # via -r requirements.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Met een leeg compile-doel hoort de stub de afwijkende body te "
        f"schrijven, wat een desync geeft.\n{resultaat.stdout}{resultaat.stderr}"
    )
    assert "1.1.0" in resultaat.stderr


def test_gewijzigde_hash_geeft_desync(tmp_path):
    """Een lock met een andere hash dan de resolve moet rood worden.

    Dit is de faalmodus met de grootste impact: versie en pakketnaam kloppen,
    alleen de hash niet. De gate gaf hier eerder groen omdat de lock inclusief
    hashes als versievoorkeur werd meegegeven en uv die overnam in plaats van te
    herberekenen — de diff vergeleek de corruptie dus met zichzelf. Geverifieerd
    met echte uv: zo een lock brak af op `uv pip install --require-hashes`.
    """
    root = _repo(tmp_path)
    gemanipuleerd = LOCK_BODY.replace("1111111", "9999999")
    (root / "requirements.txt").write_text(HEADER + gemanipuleerd, encoding="utf-8")
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Een afwijkende hash hoort de gate rood te maken.\n"
        f"{resultaat.stdout}{resultaat.stderr}"
    )
    assert "hash" in resultaat.stderr


def test_ontbrekende_hashregel_geeft_desync(tmp_path):
    """Een lock waaruit een hashregel is weggevallen moet rood worden."""
    root = _repo(tmp_path)
    zonder_hash = "voorbeeld==1.0.0\n    # via -r requirements.in\n"
    (root / "requirements.txt").write_text(HEADER + zonder_hash, encoding="utf-8")
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Een ontbrekende hashregel hoort de gate rood te maken.\n"
        f"{resultaat.stdout}{resultaat.stderr}"
    )


def test_gewijzigde_dev_hash_geeft_desync(tmp_path):
    """Ook op de dev-tak moet een afwijkende hash gevangen worden."""
    root = _repo(tmp_path)
    gemanipuleerd = DEV_LOCK_BODY.replace("2222222", "8888888")
    (root / "requirements-dev.txt").write_text(HEADER + gemanipuleerd, encoding="utf-8")
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Een afwijkende dev-hash hoort de gate rood te maken.\n"
        f"{resultaat.stdout}{resultaat.stderr}"
    )
    assert "requirements-dev.txt niet in sync" in resultaat.stderr


def test_dev_resolvefout_geeft_resolve_exitcode(tmp_path):
    """Een fout die alleen tijdens de dev-resolve optreedt heeft eigen dekking.

    De runtime-tak slaagt hier, dus dit scenario onderscheidt zich van
    `test_falende_resolve_geeft_eigen_exitcode`, waar de eerste aanroep al
    faalt.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        dev_exit_code=1,
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 2, (
        "Een dev-resolvefout hoort de resolve-exitcode te geven, niet die van "
        f"een desync.\n{resultaat.stdout}{resultaat.stderr}"
    )
    assert "requirements-dev.in niet resolven" in resultaat.stderr
    assert "OK:" not in resultaat.stdout


def test_credentials_in_uv_fout_worden_geredigeerd(tmp_path):
    """uv-stderr belandt in publieke CI-joblogs, dus geheimen eruit.

    uv noemt index-URL's in resolve-fouten. Die kunnen credentials dragen in de
    userinfo vóór de @, maar ook als query-parameter — dat tweede pad ontbrak.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        exit_code=1,
        foutmelding=(
            "error: kan https://gebruiker:GEHEIM123@index.example/simple niet "
            "bereiken, ook niet via https://index.example/simple?token=GEHEIM456"
        ),
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 2, resultaat.stderr
    assert "GEHEIM123" not in resultaat.stderr, resultaat.stderr
    assert "GEHEIM456" not in resultaat.stderr, resultaat.stderr
    # De rest van de melding moet wel leesbaar blijven, anders is de fout niet
    # meer te diagnosticeren.
    assert "index.example" in resultaat.stderr


def test_write_modus_genereert_de_locks(tmp_path):
    """`make lock` draait dit script met --write; die tak heeft eigen dekking.

    Zonder deze test kan de schrijfkant stilzwijgend stukgaan terwijl de
    checkkant groen blijft — en dan genereert `make lock` niets meer.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    (root / "requirements.txt").write_text("", encoding="utf-8")
    (root / "requirements-dev.txt").write_text("", encoding="utf-8")
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{bin_dir}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["bash", str(SCRIPT), "--write"],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode == 0, resultaat.stderr
    # Write compileert zonder --no-header, dus de stub schrijft er net als echte
    # uv een header boven. De body eronder moet nog steeds exact kloppen.
    runtime = (root / "requirements.txt").read_text(encoding="utf-8")
    dev = (root / "requirements-dev.txt").read_text(encoding="utf-8")
    assert runtime.startswith("#"), runtime
    assert runtime.endswith(LOCK_BODY), runtime
    assert dev.startswith("#"), dev
    assert dev.endswith(DEV_LOCK_BODY), dev

    # In write-modus hoort --custom-compile-command mee, anders schrijft uv het
    # willekeurige mktemp-pad in de header: dat lekt een lokaal pad naar de repo
    # en geeft bij elke run een andere header, dus altijd een diff.
    aanroepen = (bin_dir / "argv.log").read_text(encoding="utf-8").splitlines()
    for aanroep in aanroepen:
        tokens = aanroep.split()
        assert "--custom-compile-command" in tokens, tokens
        assert "--no-header" not in tokens, tokens
        assert "--generate-hashes" in tokens, tokens


def test_write_modus_bouwt_ontbrekende_locks_op(tmp_path):
    """Een eerste opbouw moet werken zonder bestaande lockfiles.

    De oude `uv pip compile -o requirements.txt` kon een ontbrekend doel gewoon
    aanmaken. Toen check- en write-modus dezelfde preconditie deelden, gaf een
    repo met alleen `.in`-bronnen exit 3 — een regressie ten opzichte van de
    route die vervangen werd.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").unlink()
    (root / "requirements-dev.txt").unlink()
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{tmp_path / 'bin'}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["bash", str(SCRIPT), "--write"],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode == 0, f"{resultaat.stdout}{resultaat.stderr}"
    assert (root / "requirements.txt").exists()
    assert (root / "requirements-dev.txt").exists()


def test_write_laat_geen_half_bijgewerkt_lockpaar_achter(tmp_path):
    """Faalt de dev-resolve, dan mag de runtime-lock niet al gewijzigd zijn.

    De vorige volgorde schreef requirements.txt vóór de dev-compile. Een
    onoplosbare dev-dependency liet dan een bijgewerkte runtime-lock naast een
    ongewijzigde dev-lock achter — de repo in een tussentoestand.
    """
    root = _repo(tmp_path)
    oorspronkelijk = (root / "requirements.txt").read_text(encoding="utf-8")
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        dev_exit_code=1,
    )

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{tmp_path / 'bin'}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["bash", str(SCRIPT), "--write"],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode == 2, f"{resultaat.stdout}{resultaat.stderr}"
    assert (root / "requirements.txt").read_text(
        encoding="utf-8"
    ) == oorspronkelijk, "requirements.txt is gewijzigd terwijl de dev-resolve faalde"


def test_onbekend_argument_wordt_geweigerd(tmp_path):
    """Een typefout in het argument mag niet stilzwijgend als check gelden."""
    root = _repo(tmp_path)
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{tmp_path / 'bin'}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["bash", str(SCRIPT), "--wrte"],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode == 3, resultaat.stderr
    assert "onbekend argument" in resultaat.stderr


def test_make_lock_roept_de_write_modus_aan(tmp_path):
    """Ook het `lock`-target heeft functionele dekking nodig.

    `make lock-check` is gedekt, maar een `lock`-target dat succesvol niets doet
    bleef groen — en dan genereert niemand nog een lock terwijl alles er goed
    uitziet.
    """
    repo_root = SCRIPT.parent.parent.parent
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    (root / "requirements.txt").write_text("", encoding="utf-8")
    (root / "requirements-dev.txt").write_text("", encoding="utf-8")
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{bin_dir}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["make", "lock"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode == 0, f"{resultaat.stdout}{resultaat.stderr}"
    geschreven = (root / "requirements.txt").read_text(encoding="utf-8")
    assert geschreven.endswith(LOCK_BODY), (
        "make lock heeft de lock niet geschreven; een target dat niets doet "
        f"zou hier ook exit 0 geven\n{geschreven!r}"
    )
    # Alleen op de staart toetsen is te zwak: een target dat het script aanroept
    # en er daarna nog iets vóór plakt, eindigt nog steeds op LOCK_BODY terwijl
    # `make lock-check` er vervolgens op afknapt. De uitvoer moet dus precies de
    # header van de stub plus de body zijn, en niets ertussen.
    assert geschreven == VERWACHTE_WRITE_HEADER + LOCK_BODY, geschreven


def test_tempdir_wordt_opgeruimd(tmp_path):
    """De werkmap mag niet blijven staan, ook niet na een fout.

    Zonder deze assertie blijft het slopen van de opruimhandler onzichtbaar:
    de gate blijft correct oordelen en laat alleen rommel achter, wat op een
    CI-runner of dev-machine ongemerkt oploopt.
    """
    root = _repo(tmp_path)
    tmpdir = tmp_path / "tmpdir"
    tmpdir.mkdir()
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{tmp_path / 'bin'}:/usr/bin:/bin:/usr/sbin:/sbin"
    env["TMPDIR"] = str(tmpdir)

    geslaagd = subprocess.run(
        ["bash", str(SCRIPT)], capture_output=True, text=True, env=env, check=False
    )
    assert geslaagd.returncode == 0, geslaagd.stderr
    assert list(tmpdir.iterdir()) == [], "werkmap blijft staan na een geslaagde run"

    # En ook op het faalpad.
    (root / "requirements.txt").write_text(
        HEADER + "voorbeeld==9.9.9\n    # via -r requirements.in\n", encoding="utf-8"
    )
    gefaald = subprocess.run(
        ["bash", str(SCRIPT)], capture_output=True, text=True, env=env, check=False
    )
    assert gefaald.returncode == 1, gefaald.stderr
    assert list(tmpdir.iterdir()) == [], "werkmap blijft staan na een gefaalde run"


def test_make_target_faalt_bij_desync(tmp_path):
    """Toets de make-bedrading functioneel, niet op de tekst van `make -n`.

    Een tekstcontrole op `make -n`-uitvoer is te zwak: een target als
    `@true # bash scripts/ci/check_lock_sync.sh` bevat het scriptpad nog steeds
    en zou groen blijven terwijl `make lock-check` succesvol niets doet. Deze
    test draait het target écht, tegen een fixture-repo met een desync, en
    verwacht een niet-nulstatus.
    """
    repo_root = SCRIPT.parent.parent.parent
    root = _repo(tmp_path)
    # Maak de lock aantoonbaar out of sync met de bron.
    (root / "requirements.txt").write_text(
        HEADER + "voorbeeld==9.9.9\n    # via -r requirements.in\n", encoding="utf-8"
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    env["PATH"] = f"{tmp_path / 'bin'}:/usr/bin:/bin:/usr/sbin:/sbin"
    resultaat = subprocess.run(
        ["make", "lock-check"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )

    assert resultaat.returncode != 0, (
        "make lock-check hoort te falen op een desynchrone lock; een target dat "
        f"niets doet zou hier groen zijn.\n{resultaat.stdout}{resultaat.stderr}"
    )
    assert "niet in sync" in resultaat.stderr, resultaat.stderr


def test_langere_header_wordt_correct_gestript(tmp_path):
    """Het commentaarblok wordt op inhoud gestript, niet op een vast regelaantal.

    Zou het script een vaste `sed '1,2d'` gebruiken, dan zet één extra
    headerregel — een uv-upgrade die de header verlengt, of iemand die een
    toelichting bovenaan zet — de gate permanent rood op iets wat `make lock`
    niet oplost. Dat is dezelfde faalklasse als DEF-559.
    """
    root = _repo(tmp_path)
    langere_header = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile\n"
        "# Extra toelichtingsregel die uv of een mens kan toevoegen.\n"
    )
    (root / "requirements.txt").write_text(langere_header + LOCK_BODY, encoding="utf-8")
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De lock is inhoudelijk in sync; rood betekent dat de header op een "
        f"vast regelaantal wordt gestript.\n{resultaat.stderr}"
    )


def test_index_directive_in_de_lock_wordt_gezien(tmp_path):
    """Een pip-directive bovenaan de lock mag niet als header wegvallen.

    `--index-url` en verwanten verleggen de installatiebron en zijn daarmee de
    enige injectievector die `--require-hashes` niet afdekt. Ze beginnen niet
    met `#`, dus het strippen van het commentaarblok mag ze niet meenemen.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER + "--index-url https://kwaadaardig.example/simple\n" + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Een index-directive in de lock die niet uit de resolve komt, hoort de "
        f"gate rood te maken.\n{resultaat.stdout}{resultaat.stderr}"
    )
    assert "index-url" in resultaat.stderr


def test_compileer_geeft_de_juiste_vlaggen_mee(tmp_path):
    """Toets welke vlaggen uv krijgt, niet alleen wat hij teruggeeft.

    Zonder deze controle blijft het wegvallen van `--no-header` of van de
    `-c requirements.txt`-constraint onzichtbaar: de stub schrijft dan nog
    steeds een passende body en alle andere tests blijven groen.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, bin_dir)
    assert resultaat.returncode == 0, resultaat.stderr

    aanroepen = (bin_dir / "argv.log").read_text(encoding="utf-8").splitlines()
    assert len(aanroepen) == 2, f"verwacht twee uv-aanroepen, kreeg: {aanroepen}"

    # Op tokens vergelijken, niet op substrings: "--generate-hashes" zit ook in
    # "--generate-hashes-BROKEN", en "-c requirements.txt" in
    # "-c requirements.txt.bak". Substringmatching zou die mutaties missen.
    runtime_tokens = aanroepen[0].split()
    dev_tokens = aanroepen[1].split()

    for tokens in (runtime_tokens, dev_tokens):
        assert tokens[:2] == ["pip", "compile"], tokens
        assert "--no-header" in tokens, tokens
        assert "--generate-hashes" in tokens, tokens
        assert "--universal" in tokens, tokens
        assert "-o" in tokens, tokens

    assert "-c" in dev_tokens, dev_tokens
    assert "-c" not in runtime_tokens, runtime_tokens

    # De dev-constraint moet een relatief pad zijn. Een absoluut tijdelijk pad
    # belandt in de `# via`-annotaties van de dev-lock, waardoor elke run een
    # andere lock oplevert en de gate niet-deterministisch wordt.
    constraint = dev_tokens[dev_tokens.index("-c") + 1]
    assert constraint == "requirements.txt", dev_tokens
    assert not constraint.startswith("/"), dev_tokens

    # In check-modus hoort --no-header erbij; in write-modus juist niet, want
    # dan documenteert de header het reproductiecommando.
    for tokens in (runtime_tokens, dev_tokens):
        assert "--custom-compile-command" not in tokens, tokens


def test_ontbrekend_pakket_in_de_lock_geeft_desync(tmp_path):
    """De faalmodus die deze gate bestaansrecht geeft.

    In PR #417 viel `setuptools` uit requirements.txt terwijl requirements.in
    het pinde, en dat landde ongemerkt op main. De andere desync-tests muteren
    alleen een versienummer; deze toetst een pakket dat de resolve wél oplevert
    maar dat in de gecommitte lock ontbreekt.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY + "ontbrekend==3.0.0\n    # via -r requirements.in\n",
        dev_body=DEV_LOCK_BODY,
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements.txt niet in sync" in resultaat.stderr
    assert "ontbrekend" in resultaat.stderr


def test_afwijkende_runtime_lock_geeft_desync(tmp_path):
    """Een resolve die afwijkt van requirements.txt moet exit 1 geven."""
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body="voorbeeld==9.9.9\n    # via -r requirements.in\n",
        dev_body=DEV_LOCK_BODY,
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements.txt niet in sync" in resultaat.stderr
    # De diff moet zichtbaar zijn, anders is de melding niet diagnosticeerbaar.
    assert "9.9.9" in resultaat.stderr


def test_afwijkende_dev_lock_geeft_desync(tmp_path):
    """De dev-tak heeft een eigen constraint en vergelijking en moet apart falen.

    Zonder deze test dekt niets af dat de dev-tak niet stilzwijgend altijd
    slaagt; de runtime-tak zegt daar niets over.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body="voorbeeld-dev==8.8.8\n    # via -r requirements-dev.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements-dev.txt niet in sync" in resultaat.stderr
    assert "8.8.8" in resultaat.stderr


def test_falende_resolve_geeft_eigen_exitcode(tmp_path):
    """Een uv die niet kan resolven is een andere fout dan een verouderde lock."""
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY, exit_code=1
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 2, resultaat.stderr
    assert "niet resolven" in resultaat.stderr


def test_ontbrekend_bronbestand_geeft_preconditiefout(tmp_path):
    """Een onvolledige repo is geen desync maar een randvoorwaarde-fout."""
    root = _repo(tmp_path)
    (root / "requirements-dev.in").unlink()
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 3, resultaat.stderr
    assert "requirements-dev.in ontbreekt" in resultaat.stderr


def test_ontbrekende_uv_geeft_preconditiefout(tmp_path):
    """Zonder uv moet de gate dat melden, niet doen alsof de lock stuk is."""
    root = _repo(tmp_path)

    resultaat = _draai(root, None)

    assert resultaat.returncode == 3, resultaat.stderr
    assert "uv niet gevonden" in resultaat.stderr


def test_custom_compile_command_heeft_een_vaste_waarde(tmp_path):
    """De headerwaarde moet een vast commando zijn, niet het compile-doel.

    Toetsen dát de vlag meegaat is te zwak: geef je er het tijdelijke pad aan
    mee, dan staat de vlag er nog steeds en blijft die assertie groen — terwijl
    de header weer een willekeurige /var/folders-locatie bevat en elke run een
    andere lock geeft. De waarde zelf is wat reproduceerbaarheid oplevert.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai_write(root, bin_dir)

    assert resultaat.returncode == 0, resultaat.stderr
    aanroepen = (bin_dir / "argv.log").read_text(encoding="utf-8").splitlines()
    assert aanroepen, "de stub is niet aangeroepen"
    for aanroep in aanroepen:
        tokens = aanroep.split()
        index = tokens.index("--custom-compile-command")
        assert tokens[index + 1 : index + 3] == ["make", "lock"], (
            "de headerwaarde moet het reproduceerbare commando zijn, niet een "
            f"pad: {tokens}"
        )


def test_schrijffout_laat_de_bestaande_lock_ongemoeid(tmp_path):
    """Schrijven gaat via een sibling en een mv, niet met een directe cp.

    Een rechtstreekse `cp` naar het doel kan bij een fout halverwege een
    afgekapt bestand achterlaten. Een niet-schrijfbare repo-map discrimineert
    tussen beide implementaties: de sibling kan er niet worden aangemaakt, dus
    faalt de run vóór er iets wijzigt, terwijl een directe cp naar het bestaande
    bestand wél zou slagen en de lock zou overschrijven.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)
    oorspronkelijk = (root / "requirements.txt").read_text(encoding="utf-8")

    root.chmod(0o555)
    try:
        resultaat = _draai_write(root, bin_dir)
    finally:
        root.chmod(0o755)

    assert resultaat.returncode == 3, f"{resultaat.stdout}{resultaat.stderr}"
    achteraf = (root / "requirements.txt").read_text(encoding="utf-8")
    assert (
        achteraf == oorspronkelijk
    ), "de lock is overschreven terwijl de schrijfactie niet kon slagen"


def test_tempdir_wordt_opgeruimd_in_write_modus(tmp_path):
    """Ook de write-tak moet zijn werkmap opruimen, op beide paden.

    De opruiming en de rollback delen één EXIT-trap. Sloopt een wijziging de
    opruimkant daarvan, dan blijft de gate correct oordelen en lopen alleen de
    tempdirs op — precies het soort regressie dat niemand opmerkt.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    tmpdir = tmp_path / "tmpdir"
    tmpdir.mkdir()
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    geslaagd = _draai_write(root, bin_dir, tmpdir=tmpdir)
    assert geslaagd.returncode == 0, geslaagd.stderr
    assert list(tmpdir.iterdir()) == [], "werkmap blijft staan na een geslaagde write"

    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY, dev_exit_code=1)
    gefaald = _draai_write(root, bin_dir, tmpdir=tmpdir)
    assert gefaald.returncode == 2, gefaald.stderr
    assert list(tmpdir.iterdir()) == [], "werkmap blijft staan na een gefaalde write"


def test_onbekende_querysleutel_wordt_ook_geredigeerd(tmp_path):
    """De redactie mag niet afhangen van hoe een sleutelnaam eruitziet.

    Een tekenklasse voor de sleutel ([A-Za-z0-9_.-]) laat een percent-encoded
    of anderszins exotische parameter buiten de match vallen, en dan passeert de
    hele parameter — inclusief de waarde — ongemaskeerd naar het joblog.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        exit_code=1,
        foutmelding=(
            "error: https://index.example/simple?api%2Dtoken=GEHEIM789 "
            "en https://index.example/simple?x~auth=GEHEIM012 falen"
        ),
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 2, resultaat.stderr
    assert "GEHEIM789" not in resultaat.stderr, resultaat.stderr
    assert "GEHEIM012" not in resultaat.stderr, resultaat.stderr
    assert "index.example" in resultaat.stderr


def test_extra_argument_naast_write_wordt_geweigerd(tmp_path):
    """Een tweede argument mag niet stilzwijgend wegvallen.

    De case-controle kijkt alleen naar $1. Zonder de telling erbij accepteert
    het script `--write --oops` als een gewone write, en verdwijnt een typefout
    of een bedoelde vlag ongemerkt.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai_write(root, bin_dir, "--oops")

    assert resultaat.returncode == 3, f"{resultaat.stdout}{resultaat.stderr}"
    assert "te veel argumenten" in resultaat.stderr


def test_rollback_verwijdert_een_lock_die_er_niet_was(tmp_path):
    """Een gefaalde eerste opbouw mag geen halve lock achterlaten.

    Bij een ontbrekende requirements.txt is er niets om naar terug te kopiëren.
    Een rollback die alleen een backup kent, laat de zojuist geschreven
    runtime-lock dan gewoon staan — naast een dev-lock die er nog niet is. De
    gebruiker committeert dan een lock die nooit uit een geslaagde resolutie is
    gekomen.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").unlink()
    (root / "requirements-dev.txt").unlink()
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY, dev_exit_code=1)

    resultaat = _draai_write(root, bin_dir)

    assert resultaat.returncode == 2, f"{resultaat.stdout}{resultaat.stderr}"
    assert not (root / "requirements.txt").exists(), (
        "requirements.txt is blijven staan terwijl hij er vóór de gefaalde run "
        "niet was"
    )
    assert not (root / "requirements-dev.txt").exists()


# ------------- Reviewronde PR 419: round-trip, rollback, redactie


def test_write_gevolgd_door_check_is_groen(tmp_path):
    """Wat `--write` schrijft, moet dezelfde gate direct goedkeuren.

    Dit is de invariant waarvoor deze story bestaat: genereren en verifiëren
    delen één implementatie, zodat de vlaggenset en de versievoorkeur niet
    uiteen kunnen lopen. Losse tests op beide takken bewijzen dat niet — een
    vlag die maar aan één kant zit houdt ze allebei groen, terwijl de gate
    direct na `make lock` rood staat. Dat is precies de faalklasse van DEF-559.

    De stub schrijft in write-modus wél een header en in check-modus niet, net
    als echte uv. Daardoor loopt de headerstrip van `vergelijk()` hier echt
    mee in plaats van tegen een handgeschreven fixture-header.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    # Zonder bestaande locks beginnen, zodat write ze werkelijk opbouwt.
    (root / "requirements.txt").unlink()
    (root / "requirements-dev.txt").unlink()
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    geschreven = _draai_write(root, bin_dir)
    assert geschreven.returncode == 0, geschreven.stderr

    # Opzetcontrole: draagt de write-uitvoer geen header, dan toetst de check
    # hieronder de headerstrip niet en bewijst deze test minder dan hij lijkt.
    for naam in ("requirements.txt", "requirements-dev.txt"):
        inhoud = (root / naam).read_text(encoding="utf-8")
        assert inhoud.startswith("#"), f"{naam} draagt geen header: {inhoud[:40]!r}"

    gecontroleerd = _draai(root, bin_dir)

    assert gecontroleerd.returncode == 0, (
        "de gate wijst af wat hij zojuist zelf heeft geschreven; genereren en "
        f"verifiëren lopen uiteen\n{gecontroleerd.stdout}{gecontroleerd.stderr}"
    )


def test_mislukte_schrijfactie_meldt_geen_valse_rollback(tmp_path):
    """Alleen wat werkelijk gemuteerd is, mag worden teruggedraaid.

    De transactie stond aan vóór de eerste schrijfactie kon slagen. Faalde die,
    dan draaide de EXIT-trap alsnog beide locks terug — bestanden die niemand
    had aangeraakt. In een read-only map faalt dat herstel ook, dus las de
    gebruiker dat terugdraaien was MISLUKT, kreeg hij de opdracht handmatig te
    herstellen uit een werkmap, en bleef die werkmap staan omdat de backups
    daar het enige exemplaar leken. Alle drie onterecht: er was niets gewijzigd.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    tmpdir = tmp_path / "tmpdir"
    tmpdir.mkdir()
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)
    oorspronkelijk = (root / "requirements.txt").read_text(encoding="utf-8")

    root.chmod(0o555)
    try:
        resultaat = _draai_write(root, bin_dir, tmpdir=tmpdir)
    finally:
        root.chmod(0o755)

    assert resultaat.returncode == 3, f"{resultaat.stdout}{resultaat.stderr}"
    assert (root / "requirements.txt").read_text(encoding="utf-8") == oorspronkelijk

    assert "kon NIET worden teruggedraaid" not in resultaat.stderr, (
        "rollback gemeld voor een bestand dat deze run nooit heeft gemuteerd:\n"
        f"{resultaat.stderr}"
    )
    assert "herstel handmatig" not in resultaat.stderr, resultaat.stderr
    assert (
        list(tmpdir.iterdir()) == []
    ), "werkmap blijft staan terwijl er niets te herstellen viel"


def test_credentials_in_de_desync_diff_worden_geredigeerd(tmp_path):
    """Ook de diff-uitvoer landt in publieke joblogs.

    De resolve-fout ging al door de redactie, de desync-diff niet — terwijl
    juist de lock een index-directive met credentials kan dragen, en zo een
    regel gegarandeerd in de diff belandt zodra hij niet uit de resolve komt.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER
        + "--index-url https://gebruiker:GEHEIM123@index.example/simple?token=GEHEIM456\n"
        + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "GEHEIM123" not in resultaat.stderr, resultaat.stderr
    assert "GEHEIM456" not in resultaat.stderr, resultaat.stderr
    # De diagnose moet bruikbaar blijven, anders is de melding waardeloos.
    assert "index-url" in resultaat.stderr, resultaat.stderr
    assert "index.example" in resultaat.stderr, resultaat.stderr


def _mv_die_slaagt_maar_faalt(bin_dir: Path) -> None:
    """Zet een `mv` op PATH die hernoemt en dáárna een foutstatus geeft.

    Modelleert twee echte gevallen tegelijk: een `mv` die de rename voltooit maar
    non-zero retourneert, en een signaal dat toeslaat tussen de voltooide rename
    en het moment waarop het script vastlegt dat er gemuteerd is.
    """
    mv = bin_dir / "mv"
    mv.write_text('#!/usr/bin/env bash\n/bin/mv "$@"\nexit 1\n', encoding="utf-8")
    mv.chmod(0o755)


def test_mutatie_die_zich_als_mislukt_meldt_wordt_teruggedraaid(tmp_path):
    """Een mv die hernoemt en daarna faalt, laat de lock niet gewijzigd achter.

    De transactievlag stond ná de `schrijf`-aanroep, dus pas nadat `mv` was
    teruggekeerd. Voltooide die de rename maar meldde hij een fout — of sloeg
    er een signaal toe tussen de rename en de vlagtoekenning — dan was de lock
    vervangen terwijl de vlag op 0 bleef. De trap herstelde dan niets en gooide
    de backups weg: een gemuteerde repo zonder weg terug.

    De vlag hoort daarom vóór de `mv` te staan en niet erna: hij betekent "het
    doel kan vanaf hier gemuteerd zijn", en bij twijfel draait een transactie
    terug. De `cp` erboven raakt het doel niet, dus die houdt de vlag op 0 —
    daar blijft een gefaalde voorbereiding dus terecht zonder rollback.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)
    _mv_die_slaagt_maar_faalt(bin_dir)
    oorspronkelijk = (root / "requirements.txt").read_text(encoding="utf-8")

    resultaat = _draai_write(root, bin_dir)

    assert resultaat.returncode == 3, f"{resultaat.stdout}{resultaat.stderr}"
    assert (root / "requirements.txt").read_text(encoding="utf-8") == oorspronkelijk, (
        "de lock is vervangen door een mv die zich als mislukt meldde, en niet "
        "teruggedraaid; de transactie miste de mutatie"
    )


def test_credentials_over_een_line_continuation_worden_geredigeerd(tmp_path):
    """Een URL mag zich niet aan de redactie onttrekken door zich te splitsen.

    Requirements-bestanden voegen een regel die op een backslash eindigt samen
    met de volgende. De redactie werkte per fysieke regel, dus een directive die
    zijn credential over twee regels verdeelde ontsnapte: bij de userinfo-vorm
    staan `://` en `@` niet meer op dezelfde regel, en bij de queryvorm werd
    alleen de backslash gemaskeerd terwijl de waarde eronder bleef staan.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER
        + "--index-url https://gebruiker:\\\nGEHEIM789@index.example/simple\n"
        + "--extra-index-url https://index.example/extra?token=\\\nGEHEIM012\n"
        + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "GEHEIM789" not in resultaat.stderr, resultaat.stderr
    assert "GEHEIM012" not in resultaat.stderr, resultaat.stderr
    # De hostnamen blijven staan, anders is de melding niet te diagnosticeren.
    assert "index.example" in resultaat.stderr, resultaat.stderr


def test_ingesprongen_userinfo_continuation_wordt_geredigeerd(tmp_path):
    """Een vervolgregel mag zijn geheim niet achter inspringing verbergen.

    Het samenvoegen haalde de diff-prefix van de vervolgregel weg, maar liet de
    inspringing staan. De userinfo-regex eist niet-witruimte tussen `://` en de
    `@`, dus `gebruiker:    GEHEIM@host` matchte niet en het wachtwoord ging
    ongemaskeerd naar stderr — en daarmee naar het publieke joblog.

    Inspringing is hier geen kunstgreep: pip en uv accepteren een ingesprongen
    vervolgregel, en menig editor voegt haar vanzelf toe.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER
        + "--index-url https://gebruiker:\\\n    GEHEIM_INDENT@index.example/simple\n"
        + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "GEHEIM_INDENT" not in resultaat.stderr, resultaat.stderr
    # Diagnose blijft nodig: host en directive horen zichtbaar te blijven.
    assert "index-url" in resultaat.stderr, resultaat.stderr
    assert "index.example" in resultaat.stderr, resultaat.stderr


def test_ingesprongen_querywaarde_continuation_wordt_geredigeerd(tmp_path):
    """Dezelfde inspringing verbergt ook een afgebroken querywaarde.

    Na de `=` volgde eerst witruimte, en de queryregex eist daar direct een
    waarde. De maskering stopte dus op de spaties en liet het token erachter
    staan. De sleutelnaam zelf blijft wel zichtbaar; die is diagnostisch en
    geen geheim.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER
        + "--extra-index-url https://index.example/extra?token=\\\n    GEHEIM_QUERY\n"
        + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "GEHEIM_QUERY" not in resultaat.stderr, resultaat.stderr
    assert "token=" in resultaat.stderr, resultaat.stderr
    assert "index.example" in resultaat.stderr, resultaat.stderr
