"""Tests voor scripts/ci/check_lock_sync.sh (DEF-559/DEF-711).

Deze gate bewaakt of de gecommitte lock hoort bij de gecommitte .in-bron. Hij
stond eerder structureel rood — zelfs direct na `make lock` — en werd daarom
genegeerd, waarna een echte desync ongemerkt op main landde: `setuptools` viel
uit requirements.txt terwijl requirements.in het pinde. Zonder test bewaakt niets
dat de gate zijn discriminerende vermogen houdt.

`uv` wordt gestubd. Een echte resolve kost seconden en netwerk, en zou de test
afhankelijk maken van PyPI-beschikbaarheid; de stub maakt alle uitkomsten
deterministisch en toetst precies wat dit script zelf doet — het vergelijken van
de resolve-uitvoer met de gecommitte lock, en het onderscheiden van de
foutklassen.

Exit-codes van het script: 0 sync, 1 desync, 2 resolve-fout, 3 preconditie.
Die zijn alleen zichtbaar bij een directe aanroep; `make lock-check` vertaalt
elke fout naar make-exitcode 2.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit]

SCRIPT = (
    Path(__file__).parent.parent.parent.parent / "scripts" / "ci" / "check_lock_sync.sh"
)

# De eerste twee regels van een uv-lock zijn de header; het script strips die
# voor de vergelijking, omdat de check met --no-header compileert.
HEADER = "# This file was autogenerated by uv via the following command:\n#    uv pip compile\n"
LOCK_BODY = "voorbeeld==1.0.0\n    # via -r requirements.in\n"
DEV_LOCK_BODY = "voorbeeld-dev==2.0.0\n    # via -r requirements-dev.in\n"


def _fake_uv(
    bin_dir: Path,
    *,
    runtime_body: str,
    dev_body: str,
    exit_code: int = 0,
    body_zonder_voorkeur: str | None = None,
    dev_body_zonder_voorkeur: str | None = None,
) -> None:
    """Zet een uv-stub op PATH die het -o-doel vult met de opgegeven inhoud.

    Het script roept uv twee keer aan: eerst voor requirements.in, daarna voor
    requirements-dev.in (herkenbaar aan het eerste positionele argument).

    `body_zonder_voorkeur` bootst uv-gedrag na dat cruciaal is voor deze gate:
    een bestaand `-o`-bestand geldt als versievoorkeur. Is dat bestand er niet
    (of leeg), dan resolvet uv vrij en kiest hij de nieuwste versies. Met die
    parameter schrijft de stub een afwijkende body wanneer het doel leeg is,
    zodat een test kan aantonen dat het script de lock daadwerkelijk als
    voorkeur meegeeft.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    uv = bin_dir / "uv"
    vrije_body = (
        body_zonder_voorkeur if body_zonder_voorkeur is not None else runtime_body
    )
    dev_vrije_body = (
        dev_body_zonder_voorkeur if dev_body_zonder_voorkeur is not None else dev_body
    )
    # De stub legt zijn volledige argv vast, zodat tests kunnen toetsen wélke
    # vlaggen het script meegeeft. Zonder die controle blijft het wegvallen van
    # -c of --no-header onzichtbaar: de gate gaat dan stuk terwijl alle tests
    # groen blijven.
    argv_log = bin_dir / "argv.log"
    uv.write_text(
        "#!/usr/bin/env bash\n"
        f'printf "%s\\n" "$*" >> {str(argv_log)!r}\n'
        f"if [ {exit_code} -ne 0 ]; then\n"
        '  echo "error: kan niet resolven" >&2\n'
        f"  exit {exit_code}\n"
        "fi\n"
        "bron=$3\n"
        'doel=""\n'
        'prev=""\n'
        'for arg in "$@"; do\n'
        '  if [ "$prev" = "-o" ]; then doel=$arg; fi\n'
        "  prev=$arg\n"
        "done\n"
        'case "$bron" in\n'
        # %b, niet %s: de body komt als Python-repr binnen, dus met \n-escapes
        # die de shell nog moet interpreteren.
        "  *requirements-dev.in)\n"
        '    if [ -s "$doel" ]; then\n'
        f"      printf '%b' {dev_body!r} > \"$doel\"\n"
        "    else\n"
        f"      printf '%b' {dev_vrije_body!r} > \"$doel\"\n"
        "    fi\n"
        "    ;;\n"
        "  *)\n"
        '    if [ -s "$doel" ]; then\n'
        f"      printf '%b' {runtime_body!r} > \"$doel\"\n"
        "    else\n"
        f"      printf '%b' {vrije_body!r} > \"$doel\"\n"
        "    fi\n"
        "    ;;\n"
        "esac\n",
        encoding="utf-8",
    )
    uv.chmod(0o755)


def _repo(tmp_path: Path) -> Path:
    """Bouw een minimale repo-structuur met .in-bronnen en locks."""
    root = tmp_path / "repo"
    root.mkdir()
    (root / "requirements.in").write_text("voorbeeld==1.0.0\n", encoding="utf-8")
    (root / "requirements-dev.in").write_text(
        "voorbeeld-dev==2.0.0\n", encoding="utf-8"
    )
    (root / "requirements.txt").write_text(HEADER + LOCK_BODY, encoding="utf-8")
    (root / "requirements-dev.txt").write_text(HEADER + DEV_LOCK_BODY, encoding="utf-8")
    return root


def _draai(root: Path, bin_dir: Path | None) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    env["LOCK_SYNC_ROOT"] = str(root)
    # Beperk PATH tot de stub plus de systeempaden die bash/diff/sed leveren,
    # zodat een echte uv uit de dev-omgeving de test niet stilletjes overneemt.
    basis = "/usr/bin:/bin:/usr/sbin:/sbin"
    env["PATH"] = f"{bin_dir}:{basis}" if bin_dir else basis
    return subprocess.run(
        ["bash", str(SCRIPT)],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )


def test_lock_in_sync_geeft_exit_0(tmp_path):
    """De gate slaagt wanneer de resolve gelijk is aan de gecommitte lock."""
    root = _repo(tmp_path)
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, resultaat.stderr
    assert "OK:" in resultaat.stdout


def test_lock_wordt_als_versievoorkeur_meegegeven(tmp_path):
    """De kern van DEF-559: de check moet dezelfde voorkeur krijgen als `make lock`.

    uv gebruikt een bestaand -o-bestand als versievoorkeur. Kopieert het script
    de lock niet naar het compile-doel, dan resolvet uv vrij en kiest hij de
    nieuwste versies — waarna de gate rood staat op niets meer dan een upstream
    release. Precies zo faalde deze gate structureel, zelfs direct na `make lock`.

    De stub schrijft een afwijkende body zodra het doel leeg is, dus deze test
    wordt rood als de kopieerstap uit het script verdwijnt.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        body_zonder_voorkeur="voorbeeld==1.1.0\n    # via -r requirements.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De gate hoort groen te zijn: de lock is geldig. Rood betekent dat de "
        f"versievoorkeur niet is meegegeven.\n{resultaat.stderr}"
    )


def test_dev_lock_wordt_als_versievoorkeur_meegegeven(tmp_path):
    """Ook de dev-tak moet zijn lock als voorkeur meekrijgen.

    Het script kopieert twee locks naar het compile-doel. Beide takken kunnen
    onafhankelijk regresseren, dus dekking van de runtime-tak zegt hier niets.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body=DEV_LOCK_BODY,
        dev_body_zonder_voorkeur="voorbeeld-dev==2.1.0\n    # via -r requirements-dev.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De dev-lock is geldig; rood betekent dat de versievoorkeur voor de "
        f"dev-tak niet is meegegeven.\n{resultaat.stderr}"
    )


def test_langere_header_wordt_correct_gestript(tmp_path):
    """Het commentaarblok wordt op inhoud gestript, niet op een vast regelaantal.

    Zou het script een vaste `sed '1,2d'` gebruiken, dan zet één extra
    headerregel — een uv-upgrade die de header verlengt, of iemand die een
    toelichting bovenaan zet — de gate permanent rood op iets wat `make lock`
    niet oplost. Dat is dezelfde faalklasse als DEF-559.
    """
    root = _repo(tmp_path)
    langere_header = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile\n"
        "# Extra toelichtingsregel die uv of een mens kan toevoegen.\n"
    )
    (root / "requirements.txt").write_text(langere_header + LOCK_BODY, encoding="utf-8")
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 0, (
        "De lock is inhoudelijk in sync; rood betekent dat de header op een "
        f"vast regelaantal wordt gestript.\n{resultaat.stderr}"
    )


def test_index_directive_in_de_lock_wordt_gezien(tmp_path):
    """Een pip-directive bovenaan de lock mag niet als header wegvallen.

    `--index-url` en verwanten verleggen de installatiebron en zijn daarmee de
    enige injectievector die `--require-hashes` niet afdekt. Ze beginnen niet
    met `#`, dus het strippen van het commentaarblok mag ze niet meenemen.
    """
    root = _repo(tmp_path)
    (root / "requirements.txt").write_text(
        HEADER + "--index-url https://kwaadaardig.example/simple\n" + LOCK_BODY,
        encoding="utf-8",
    )
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, (
        "Een index-directive in de lock die niet uit de resolve komt, hoort de "
        f"gate rood te maken.\n{resultaat.stdout}{resultaat.stderr}"
    )
    assert "index-url" in resultaat.stderr


def test_compileer_geeft_de_juiste_vlaggen_mee(tmp_path):
    """Toets welke vlaggen uv krijgt, niet alleen wat hij teruggeeft.

    Zonder deze controle blijft het wegvallen van `--no-header` of van de
    `-c requirements.txt`-constraint onzichtbaar: de stub schrijft dan nog
    steeds een passende body en alle andere tests blijven groen.
    """
    root = _repo(tmp_path)
    bin_dir = tmp_path / "bin"
    _fake_uv(bin_dir, runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, bin_dir)
    assert resultaat.returncode == 0, resultaat.stderr

    aanroepen = (bin_dir / "argv.log").read_text(encoding="utf-8").splitlines()
    assert len(aanroepen) == 2, f"verwacht twee uv-aanroepen, kreeg: {aanroepen}"

    runtime_aanroep, dev_aanroep = aanroepen
    for aanroep in (runtime_aanroep, dev_aanroep):
        assert "--no-header" in aanroep, aanroep
        assert "--generate-hashes" in aanroep, aanroep
        assert "--universal" in aanroep, aanroep
    assert "-c requirements.txt" in dev_aanroep, dev_aanroep
    assert "-c requirements.txt" not in runtime_aanroep, runtime_aanroep


def test_ontbrekend_pakket_in_de_lock_geeft_desync(tmp_path):
    """De faalmodus die deze gate bestaansrecht geeft.

    In PR #417 viel `setuptools` uit requirements.txt terwijl requirements.in
    het pinde, en dat landde ongemerkt op main. De andere desync-tests muteren
    alleen een versienummer; deze toetst een pakket dat de resolve wél oplevert
    maar dat in de gecommitte lock ontbreekt.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY + "ontbrekend==3.0.0\n    # via -r requirements.in\n",
        dev_body=DEV_LOCK_BODY,
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements.txt niet in sync" in resultaat.stderr
    assert "ontbrekend" in resultaat.stderr


def test_afwijkende_runtime_lock_geeft_desync(tmp_path):
    """Een resolve die afwijkt van requirements.txt moet exit 1 geven."""
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body="voorbeeld==9.9.9\n    # via -r requirements.in\n",
        dev_body=DEV_LOCK_BODY,
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements.txt niet in sync" in resultaat.stderr
    # De diff moet zichtbaar zijn, anders is de melding niet diagnosticeerbaar.
    assert "9.9.9" in resultaat.stderr


def test_afwijkende_dev_lock_geeft_desync(tmp_path):
    """De dev-tak heeft een eigen constraint en vergelijking en moet apart falen.

    Zonder deze test dekt niets af dat de dev-tak niet stilzwijgend altijd
    slaagt; de runtime-tak zegt daar niets over.
    """
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin",
        runtime_body=LOCK_BODY,
        dev_body="voorbeeld-dev==8.8.8\n    # via -r requirements-dev.in\n",
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 1, resultaat.stderr
    assert "requirements-dev.txt niet in sync" in resultaat.stderr
    assert "8.8.8" in resultaat.stderr


def test_falende_resolve_geeft_eigen_exitcode(tmp_path):
    """Een uv die niet kan resolven is een andere fout dan een verouderde lock."""
    root = _repo(tmp_path)
    _fake_uv(
        tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY, exit_code=1
    )

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 2, resultaat.stderr
    assert "niet resolven" in resultaat.stderr


def test_ontbrekend_bronbestand_geeft_preconditiefout(tmp_path):
    """Een onvolledige repo is geen desync maar een randvoorwaarde-fout."""
    root = _repo(tmp_path)
    (root / "requirements-dev.in").unlink()
    _fake_uv(tmp_path / "bin", runtime_body=LOCK_BODY, dev_body=DEV_LOCK_BODY)

    resultaat = _draai(root, tmp_path / "bin")

    assert resultaat.returncode == 3, resultaat.stderr
    assert "requirements-dev.in ontbreekt" in resultaat.stderr


def test_ontbrekende_uv_geeft_preconditiefout(tmp_path):
    """Zonder uv moet de gate dat melden, niet doen alsof de lock stuk is."""
    root = _repo(tmp_path)

    resultaat = _draai(root, None)

    assert resultaat.returncode == 3, resultaat.stderr
    assert "uv niet gevonden" in resultaat.stderr
