name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - ChrisLehnen

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        Please provide detailed information to help us evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Other ways to solve this could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocks current work)
        - High (important for workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - CI/CD Pipeline
        - Security
        - Testing
        - UI/UX
        - Backend/API
        - Database
        - Documentation
        - Configuration
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. As a developer, I want to...
        2. When working on..., I need to...

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Projects
      description: Are there examples of this feature in other projects?
      placeholder: Links to similar implementations...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Sketches
      description: If applicable, add mockups or sketches to visualize the feature
      placeholder: Drag and drop images here

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: This might require changes to...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: Check all that apply
      options:
        - label: This feature requires breaking changes
        - label: This feature affects the API
        - label: This feature requires database migrations
        - label: This feature affects security
        - label: This feature affects performance
        - label: This feature requires new dependencies

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues/features to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement
          required: true
        - label: I have described the proposed solution
          required: true
        - label: I am willing to help implement this feature
          required: false

